### ISSUE TITLE
PhpStorm CSS code completion?

### ISSUE THREAD

**Issue by rowild** [dougmacklin/generator-foundation-browserify#1]
Hi, I set up a foundation-gulp-browserify project within phpstorm, but what ever I do, I will not get autocompletion for foundation css classes. Any hint on how to accomplish that? Thank you!

**Comment by dougmacklin** [comment]
Hey @rowild, sorry for the delay. I'm currently on vacation through the 19th. I haven't worked with phpstorm but I'll look into it when I get back.

**Comment by dougmacklin** [comment]
@rowild were you able to figure anything out? I'm sorry but I don't work in php at all so I'm not familiar with your dev environment. There are autocompletion packages available for most text-editors, could you give me some info on your setup?

**Comment by rowild** [comment]
Hi, @dougmacklin, I didn't dig into that any further, because I switched to something else - which also makes troubles. SO be assured that it is my setup with phpStorm and not your generator. However, I will get back to your generator sometimes soon and will report anything I find, ok? Good luck and thank you for getting back to me!

**Comment by dougmacklin** [comment]
Sounds good, thanks @rowild!
