### ISSUE TITLE
Foundation Update to 6.3.1

### ISSUE THREAD

**Issue by ericvida** [dougmacklin/generator-foundation-browserify#6]
Foundation is now 6.3.1
I'm just learning this yeoman thing, so I don't know how to pull request that update.
@dougmacklin

**Comment by dougmacklin** [comment]
Apologies for the delay. It looks like there weren't any changes to the _app.scss or _settings.scss files, however, so there should not have been any conflicts when using this generator (was set to install the latest version of Foundation 6). I bumped the version to 6.3.1 for the sake of consistency :)

**Comment by ericvida** [comment]
Ok. thanks. Will figure it out.

**Comment by dougmacklin** [comment]
Are you experiencing any issues? Try updating the generator (either by running `yo` and going through the command prompt or just reinstalling it with `npm install -g generator-foundation-browserify`). Let me know if anything is wrong, 6.3.1 should be good to go.
