### ISSUE TITLE
Support for foundation 6.4.0

### ISSUE THREAD

**Issue by kaymccormick** [dougmacklin/generator-foundation-browserify#7]
Recent commit says that foundation 6.4.0 requires some changes. I am hoping this generator can be updated in the future.

**Comment by dougmacklin** [comment]
Hey @kaymccormick, yep I'm planning on updating it immediately following the July 4th holiday. Will let you know when it's ready!

**Comment by dougmacklin** [comment]
Hi again @kaymccormick, this generator has now been upgraded to Foundation 6.4.0! To update it, simply run `npm install -g generator-foundation-browserify` and then use it as you normally would.

I should note that the generator now defaults to use the new [XY grid](http://foundation.zurb.com/sites/docs/xy-grid.html), however the `index.html` file contains instructions on how to revert to the legacy [Flex grid](http://foundation.zurb.com/sites/docs/flex-grid.html) or [Float grid](http://foundation.zurb.com/sites/docs/grid.html) if that is desired.
